; Polybar confiuration
; ~/.config/polybar/config.ini
; https://github.com/polybar/polybar/wiki
; Alexandre Lamberty (mail@alexandrelamberty.com)

include-file = ~/.config/polybar/colors.ini
include-file = ~/.config/polybar/hardware.ini
include-file = ~/.config/polybar/modules.ini
include-file = ~/.config/polybar/custom_modules.ini
include-file = ~/.config/polybar/icons.ini

[settings] 
screenchange-reload = true

[global/wm]

[section/base]
width = 100%
height = 28
fixed-center = true
padding-left = 1 
padding-right = 1
module-margin-left = 1
module-margin-right = 1
background = ${colors.background}
foreground = ${colors.foreground}
font-0 = Iosevka Nerd Font Mono:style:Regular:size=10;3
font-1 = Iosevka Nerd Font Mono:style:Regular:size=18;4
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true

[bar/top]
inherit = section/base
modules-left = debian i3 tmux
modules-center = xwindow
modules-right = mpd vpn date tray powermenu
tray-position = right
tray-maxsize = 16
tray-background = ${colors.background}
tray-foreground = ${colors.foreground}
tray-padding = 2
tray-scale = 1.0

[bar/bottom]
inherit = section/base
bottom = true
modules-left = battery eth wlan network-down network-up network-ip
modules-center = bhop docker nodejs services vpn
modules-right = filesystem cpu temperature memory alsa

