; Polybar hardware configuration
; ~/.config/polybar/hardware.conf
; These values are consumed by modules, adjust them to match your host.

[hardware]
wlan = ${env:DEFAULT_IFACE}
eth = enp0s25
battery = BAT0
battery-adapter = AC
hwmon-path = /sys/devices/platform/thinkpad_hwmon/hwmon/hwmon4/temp1_input
