; Polybar built-in modules
; ~/.config/polybar/modules/custom/modules.ini
; Alexandre Lamberty (mail@alexandrelamberty.com)

[module/apt]
type = custom/script
exec = ~/.config/polybar/scripts/system_update_apt.sh
interval = 3600
label = %output%
format = <label>
format-prefix = %{T2}ﯟ%{T-}
format-prefix-foreground = ${colors.primary}
format-prefix-padding-right = 2

[module/bhop]
type = custom/script
exec = ~/.config/polybar/scripts/bhop.sh
interval = 3600
label = %output%€
format = <label>
format-prefix = "%{T2}󱨛%{T-}"
format-prefix-foreground = ${colors.orange}
format-prefix-padding-right = 2

[module/calendar]
type = custom/script
exec = date '+%Y-%m-%d %H:%M:%S'
interval = 1
label = %output%
format = <label>
format-prefix = %{T2}%{T-}
format-prefix-foreground = ${colors.highlight}
format-prefix-padding-right = 2
click-left = surf https://calendar.google.com/calendar/u/0/r

[module/chrome]
type = custom/script
exec = ~/.config/polybar/scripts/chrome_process.sh
interval = 3600
label = %output%
format = <label>
format-prefix = %{T2}%{T-}
format-prefix-foreground = ${colors.red}
format-prefix-padding-right = 2

[module/debian]
type = custom/text
click-left = ~/.config/rofi/scripts/system.sh
format = %{T2}%{T-}
format-foreground = ${colors.orange}
format-padding = 1

; https://github.com/polybar/polybar/wiki/Module:-menu
[module/powermenu]
type = custom/menu
expand-right = false

format-spacing = 1
format-foreground = ${colors.primary}

label-open = %{T2}%{T-}
label-open-foreground = ${colors.primary}

label-close = %{T2}%{T-}
label-close-foreground = ${colors.primary}

label-separator = " "

menu-0-0 = Lock
menu-0-0-foreground = #fba922
menu-0-0-exec = menu-open-1
menu-0-1 = Logout
menu-0-1-foreground = #fba922
menu-0-1-exec = menu-open-2
menu-0-2 = Reboot
menu-0-2-foreground = #fba922
menu-0-2-exec = menu-open-3
menu-0-3 = Shutdown
menu-0-3-foreground = #fba922
menu-0-3-exec = menu-open-4
menu-1-0 = Lock
menu-1-0-foreground = #ff5555
menu-1-0-exec = i3lock
menu-2-0 = Logout
menu-2-0-foreground = #ff5555
menu-2-0-exec = i3-msg exit
menu-3-0 = Reboot
menu-3-0-foreground = #ff5555
menu-3-0-exec = reboot
menu-4-0 = Shutdown
menu-4-0-foreground = #ff5555
menu-4-0-exec = shutdown now

[module/scratch]
type = custom/script
exec = ~/.config/polybar/scripts/i3_scratchpads.sh
interval = 2
click-left = ~/.config/rofi/scripts/scratchpads.sh &
label = %output%
format = <label>
format-prefix = "%{T2}󱂬%{T-}"
format-prefix-foreground = ${colors.secondary}
format-prefix-padding-right = 2

[module/screencasting]
type = custom/ipc
initial = 1
click-left = polybar-msg -p %pid% hook screencasting 2
click-right = polybar-msg -p %pid% hook screencasting 3
hook1 = echo 
hook-1 = ~/.local/bin/scripts/start_webcam
hook-2 = ~/.local/bin/scripts/stop_webcam

[module/services]
type = custom/script
exec = systemctl --type=service --state=running list-units --no-pager | grep running | wc -l
interval = 10
click-left = ~/.local/bin/scripts/system_service
label = %output%
format = <label>
format-prefix = %{T2} %{T-}
format-prefix-foreground = ${colors.primary}

[module/usb]
type = custom/script
exec = ~/.config/polybar/scripts/usb_device.sh
tail = true
label = %output%
format = <label>
format-prefix = %{T2}%{T-}
format-prefix-foreground = ${colors.secondary}
format-prefix-padding-right = 2
click-left =
click-right =

[module/tasks]
type = custom/script
exec = ~/.config/polybar/scripts/tmux_session.sh
interval = 3600
label = %output%
format = <label>
format-prefix = %{T2}%{T-}
format-prefix-padding-right = 2
format-prefix-foreground = ${colors.primary}

[module/themes]
type = custom/script
exec = ~/.config/polybar/scripts/switch_theme.sh
label = %output%
format = <label>
format-foreground = ${colors.secondary}
format-prefix =
format-prefix-foreground = ${colors.primary}
format-prefix-padding-right = 2
click-left = ~/.config/polybar/scripts/switch_theme.sh toggle

[module/tmux]
type = custom/script
exec = ~/.config/polybar/scripts/tmux_session.sh
interval = 3600
click-left = ~/.config/rofi/scripts/tmux.sh &
label = %output%
format = <label>
format-prefix = "%{T2}󰆍%{T-}"
format-prefix-foreground = ${colors.secondary}
format-prefix-padding-right = 2

[module/tor]
type = custom/script
exec = ~/.config/polybar/scripts/tor_status.sh
interval = 5
label = %output%
format = <label>

[module/vpn]
type = custom/script
exec = ~/.config/polybar/scripts/vpn_status.sh
interval = 5
label = %output%
format = <label>

[module/webcam]
type = custom/ipc
initial = 1
hook-0 = echo -e 犯
hook-1 = ~/.local/bin/scripts/start_screen_recording
hook-2 = ~/.local/bin/scripts/stop_screen_recording
click-left = polybar-msg -p %pid% hook screencasting 2
click-right = polybar-msg -p %pid% hook screencasting 3

[module/windows]
type = custom/script
exec = ~/.config/polybar/scripts/i3_windows.sh
interval = 3600
click-left = ~/.config/rofi/scripts/windows.sh &
label = %output%
format = <label>
format-prefix = "%{T2}%{T-}"
format-prefix-foreground = ${colors.secondary}
format-prefix-padding-right = 2

[module/notification]
type = custom/script
exec =  ~/.config/polybar/scripts/notification.sh status
interval = 2
click-left = ~/.config/polybar/scripts/notification.sh toggle
label = %output%
