; Light Theme Colors
; ~/.config/polybar/themes/light.ini

[colors]
background = #ffffff
background-alt = #f4f4f4
foreground = #333333
foreground-alt = #555555
primary = #ffcc00
secondary = #5dbeb8
alert = #e60023
success = #5aaf6f
warn = #f68c1f
highlight = #007aff
highlight-alt = #1e90ff
accent = #ab47bc
accent-alt = #ce93d8
info = #26a69a
info-alt = #4caf50
critical = #d32f2f
critical-alt = #ff5252
orange = #FF4500
blue = #094f94
red = #FE0303
green = #00FF00