; Dark Theme Colors
; ~/.config/polybar/themes/dark.ini

[colors]
background = #0f111a
background-alt = #1a1d21
foreground = #d5c4a1
foreground-alt = #a89984
primary = #f9bc2f
secondary = #689d6a
alert = #fb4934
success = #a3be8c
warn = #e78a4e
highlight = #81a1c1
highlight-alt = #5e81ac
accent = #b48ead
accent-alt = #c896cf
info = #8fbcbb
info-alt = #88c0d0
critical = #bf616a
critical-alt = #d08770
orange = #FF4500
blue = #094f94
red = #FE0303
green = #00FF00